include="~~/profiles.conf"

### Video ###

### [General]
reset-on-next-file=pause,speed,volume
gpu-context=waylandvk
hwdec-codecs=all
gpu-api=vulkan
vo=gpu-next
hwdec=auto-safe
target-colorspace-hint-mode=source
vd-lavc-dr=yes
gpu-shader-cache=yes
vulkan-async-compute=no
vulkan-async-transfer=yes
vulkan-swap-mode=fifo
icc-profile-auto=yes
icc-intent=2
icc-3dlut-size=64x64x64

### Dithering ###
dither-depth=auto
temporal-dither=yes
dither=error-diffusion
error-diffusion=atkinson


deband=no

### Audio and Subtitles ###
volume-max=200
volume=0
slang=en,eng,English
alang=ja,jp,jpn,jap,Japanese,en,eng,English

# SUBTITLES
sub-auto=all
sub-fix-timing=yes
blend-subtitles=yes
sub-ass-override=yes
sub-ass-scale-with-window=no
sub-file-paths=sub;subs;subtitles
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes
sub-font="Segoe UI Light"
sub-font-size=40
sub-color="#FFFFFF"
sub-border-size=1.0
sub-outline-color="#FFFFFF"
sub-shadow-color="#000000"
sub-shadow-offset=0.5
sub-blur=0.0
sub-back-color="#00000000"
sub-clear-on-seek=yes
sub-delay=0
script-opts-append=trackselect-preferred_sub_lang=en/eng/english
script-opts-append=trackselect-preferred_sub_words=hearing_impaired/SDH/HI
script-opts-append=trackselect-excluded_sub_words=sign/s&s

# AUDIO
audio-file-auto=fuzzy
audio-pitch-correction=yes
audio-normalize-downmix=yes
audio-channels=7.1,5.1,stereo
audio-exclusive=no
audio-device=auto
gapless-audio=yes
audio-buffer=0.1
demuxer-readahead-secs=10
demuxer-max-bytes=200M

### Functions ###
osc=no
snap-window=yes
save-position-on-quit=yes
auto-window-resize=yes
osd-bar=no
osd-bold=yes
no-border
autofit=60%x60%
ontop=no
cursor-autohide=600
force-window=yes
idle=yes

# PLAYBACK BEHAVIOR
keep-open=no
keep-open-pause=no
force-seekable=yes
directory-mode=ignore


# YTDL FORMAT FILTER
ytdl-format=bestvideo[height<=?2160][vcodec~=av01]+bestaudio[format_id!*=-drc]/bestvideo[height<=?2160][vcodec*=vp9]+bestaudio[format_id!*=-drc]/bestvideo[height<=?2160]+bestaudio[format_id!*=-drc]/best
hls-bitrate=max

# SEEKING
hr-seek=yes
hr-seek-framedrop=no

### OSD ###
osd-font="Segoe UI"
osd-font-size=26
osd-color="#FFFFFF"
osd-border-color="#000000"
osd-border-size=1
osd-shadow-color="#000000"
osd-shadow-offset=1
osd-align-x=center
osd-align-y=top
osd-margin-y=40
osd-level=1
osd-status-msg=${filename}
osd-duration=3000

### SHADER ###
glsl-shaders-append="~~/shaders/NVScaler.glsl"
