[Deband-Medium]
deband-iterations=2
deband-threshold=64
deband-range=16
deband-grain=24

[Deband-Strong]
deband-iterations=3
deband-threshold=64
deband-range=16
deband-grain=24

[NNEDI3]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/nnedi3_nns32_win8x4.glsl;~~/shaders/ssimds.glsl"

[NNEDI3+]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/nnedi3_nns64_win8x4.glsl;~~/shaders/ssimds.glsl"

[Ravu-Zoom]
profile-desc=Suitable for most scenarios 
glsl-shaders="~~/shaders/ravu_z_ar_r3.glsl;~~/shaders/ssimds.glsl"

[FSRCNNX]
profile-desc=Suitable for HD live action
glsl-shaders="~~/shaders/F8.glsl;~~/shaders/ssimds.glsl"

[FSRCNNX+]
profile-desc=Suitable for SD live action
glsl-shaders="~~/shaders/F16.glsl;~~/shaders/ssimds.glsl"
	
[Ani4k]
profile-desc=Suitable for most anime
glsl-shaders="~~/shaders/Ani4Kv2_ArtCNN_C4F32_i2.glsl;~~/shaders/ssimds.glsl"

[AniSD]
profile-desc=Suitable for SD anime
glsl-shaders="~~/shaders/AniSD_ArtCNN_C4F32_i4.glsl;~~/shaders/ssimds.glsl"

[Anime4K]
profile-desc=Suitable for most anime
glsl-shaders="~~/shaders/krigbl.glsl;~~/shaders/A4K_Restore_CNN_Soft_M.glsl;~~/shaders/A4K_Clamp_Highlights.glsl;~~/shaders/ssimds.glsl"

### Conditional Profiles ###

[HDR]
profile-desc=HDR
profile-cond=(p["video-params/primaries"] == "bt.2020") and ((p["video-params/gamma"] == "pq") or (p["video-params/gamma"] == "hlg"))
profile-restore=copy
icc-profile=""
icc-profile-auto=no
target-colorspace-hint=yes
target-prim=auto
target-trc=auto
#target-peak=1068 (Set to your exact peak brightness)
#sub-hdr-peak=1068 (Same as target-peak)
image-subs-hdr-peak=500
tone-mapping=auto
hdr-peak-percentile=99.95
hdr-contrast-recovery=0.30
hdr-peak-decay-rate=20.0
gamut-mapping-mode=auto
inverse-tone-mapping=no
hdr-compute-peak=yes
#target-contrast=4000 (Set to your exact contrast)
video-output-levels=full
	
[4k-Downscaling]
profile-cond=(height >= 2160 or width >= 3840)
profile-restore=copy-equal
glsl-shaders-clr
glsl-shaders="~~/shaders/ssimsr.glsl;~~/shaders/ssimds.glsl"

linear-downscaling=no

[Downmix-Audio-5.1]
profile-cond=get("audio-params/channel-count") >= 5 and get("audio-params/channel-count") < 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE"

[Downmix-Audio-7.1]
profile-cond=get("audio-params/channel-count") >= 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.3*FLC+0.3*FL+0.3*BL+0.3*SL+0.5*LFE|FR=0.5*FC+0.3*FRC+0.3*FR+0.3*BR+0.3*SR+0.5*LFE"

### Battery / Power Saving ###

[Battery]
profile-desc=Low power settings
glsl-shaders=""
dither=ordered
temporal-dither=no
scale=bilinear
cscale=bilinear
dscale=bilinear
framedrop=vo
blend-subtitles=no
demuxer-readahead-secs=3
demuxer-max-bytes=64M
audio-samplerate=44100
ytdl-format=bestvideo[height<=?1080][vcodec~=av01]+bestaudio[format_id!*=-drc]/bestvideo[height<=?1080][vcodec*=vp9]+bestaudio[format_id!*=-drc]/bestvideo[height<=?1080]+bestaudio[format_id!*=-drc]/best[height<=?1080]
