categories=sponsor,intro,outro,interaction,selfpromo,filler,preview,music_offtopic
skip_categories=sponsor,interaction,selfpromo,filler,preview
local_pattern=.*[%-%_[ %(]([%w-_][%w-_][%w-_][%w-_][%w-_][%w-_][%w-_][%w-_][%w-_][%w-_][%w-_])%]?%.[mw][kpe][v4b]m?$
