--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--ozone-platform=wayland
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,UseMultiPlaneFormatForHardwareVideo,SkiaGraphite,TouchpadOverscrollHistoryNavigation,PlatformHEVCDecoderSupport,WaylandSessionManagement,WaylandTextInputV3,WaylandUiScale,WaylandWindowDecorations
