### Video ###

### [General]
reset-on-next-file=pause,speed,volume
gpu-context=waylandvk
hwdec-codecs=all
gpu-api=vulkan
vo=gpu-next
hwdec=auto-safe
#profile=fast
#libplacebo-opts=saturation=1.15
target-colorspace-hint-mode=source

### Audio and Subtitles ###
volume-max=120
volume=0
slang=en,eng,English
alang=ja,jp,jpn,jap,Japanese,en,eng,English

### Functions ###
osc=no
snap-window
save-position-on-quit=yes
auto-window-resize= yes

### OSD ###
no-border
osd-bar=no
osd-bold=yes
osd-font-size=24
osd-font=carlito bold

### SHADER
#glsl-shaders-append="~~/shaders/Enhancers/skin_texture_amplifier.glsl"
#glsl-shaders-append="~~/shaders/Enhancers/gentle_skin_color_boost.glsl"
glsl-shaders-append="~~/shaders/NVScaler.glsl"

sub-auto=all
volume-max=200
sub-fix-timing=yes
blend-subtitles=yes
sub-ass-override=yes 
audio-file-auto=fuzzy 
audio-pitch-correction=yes
audio-normalize-downmix=yes
audio-channels=7.1,5.1,stereo
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub;subs;subtitles
