[/]
always-show-log-out=true
disable-user-extensions=false
favorite-apps=['vivaldi-stable.desktop', 'org.gnome.Nautilus.desktop', 'com.mitchellh.ghostty.desktop', 'net.nokyan.Resources.desktop', 'io.github.amit9838.mousam.desktop']
last-selected-power-profile='performance'
welcome-dialog-last-shown-version='49.2'

[extensions/Bluetooth-Battery-Meter]
circle-widget-custom-colors=['#ff7800', '#ff7800', '#15c931', '#15c931', '#15c931', '#15c931', '#15c931', '#15c931', '#15c931', '#15c931']
device-list=['{"path":"/org/bluez/hci0/dev_41_42_03_F6_72_BD","icon":"earbuds-stem","alias":"Airpods Pro","paired":false,"battery-reported":true,"qs-level":true,"indicator-mode":2,"enhanced-device":null,"connected-time":1779274200,"disconnected-time":1779274196}', '{"path":"/org/bluez/hci1/dev_41_42_03_F6_72_BD","icon":"earbuds-stem","alias":"Airpods Pro","paired":true,"battery-reported":true,"qs-level":true,"indicator-mode":2,"enhanced-device":null,"connected-time":1772289662,"disconnected-time":1772292044}', '{"path":"/org/bluez/hci0/dev_7C_C9_5E_28_4B_ED","icon":"audio-headset","alias":"Redmi Buds 3 Lite","paired":true,"battery-reported":true,"qs-level":true,"indicator-mode":2,"enhanced-device":null,"connected-time":1784884616,"disconnected-time":1784887200}', '{"path":"/org/bluez/hci0/dev_FC_58_FA_8C_87_C3","icon":"audio-headset","alias":"Hama Spirit Calypso","paired":false,"battery-reported":true,"qs-level":true,"indicator-mode":2,"enhanced-device":null,"connected-time":1784188483,"disconnected-time":1784128639}']
enable-battery-level-text=true
enable-gattbas-device=false
enable-multi-indicator-mode=true
enable-on-hover-mode=true
enable-tooltip=true
enable-upower-level-icon=false
hide-bluetooth-indicator=2
