--gtk-version=4
--enable-wayland-ime
--ignore-gpu-blocklist
--wayland-text-input-version=3
--enable-gpu-rasterization
--enable-zero-copy
--ozone-platform=wayland
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,UseMultiPlaneFormatForHardwareVideo,SkiaGraphite,TouchpadOverscrollHistoryNavigation,PlatformHEVCDecoderSupport,WaylandSessionManagement,WaylandTextInputV3,WaylandUiScale,WaylandWindowDecorations,SkiaGraphite,UseSkiaGraphite
